#!/bin/bash

IP=$(ip a s eth0|grep 'inet '|egrep -o '[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}')

sed -i "s/^server: .*$/server: ${IP}/" /etc/cobbler/settings
sed -i "s/^next_server: .*$/next_server: ${IP}/" /etc/cobbler/settings

cp /conf/* /etc/cobbler/ || true

/usr/bin/supervisord
